//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.17 at 06:28:26 AM EDT 
//


package com.radian.webserviceclient.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.radian.webserviceclient.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.radian.webserviceclient.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WMCUWGetRepInfo }
     * 
     */
    public WMCUWGetRepInfo createWMCUWGetRepInfo() {
        return new WMCUWGetRepInfo();
    }

    /**
     * Create an instance of {@link WMCUWGetRepInfoResponse }
     * 
     */
    public WMCUWGetRepInfoResponse createWMCUWGetRepInfoResponse() {
        return new WMCUWGetRepInfoResponse();
    }

    /**
     * Create an instance of {@link WMCUWGetAllUnbilledLoans }
     * 
     */
    public WMCUWGetAllUnbilledLoans createWMCUWGetAllUnbilledLoans() {
        return new WMCUWGetAllUnbilledLoans();
    }

    /**
     * Create an instance of {@link WMCUWGetAllUnbilledLoansResponse }
     * 
     */
    public WMCUWGetAllUnbilledLoansResponse createWMCUWGetAllUnbilledLoansResponse() {
        return new WMCUWGetAllUnbilledLoansResponse();
    }

    /**
     * Create an instance of {@link WMCUWGetAllUnbilledLoansForDates }
     * 
     */
    public WMCUWGetAllUnbilledLoansForDates createWMCUWGetAllUnbilledLoansForDates() {
        return new WMCUWGetAllUnbilledLoansForDates();
    }

    /**
     * Create an instance of {@link WMCUWGetAllUnbilledLoansForDatesResponse }
     * 
     */
    public WMCUWGetAllUnbilledLoansForDatesResponse createWMCUWGetAllUnbilledLoansForDatesResponse() {
        return new WMCUWGetAllUnbilledLoansForDatesResponse();
    }

    /**
     * Create an instance of {@link WMCUWGetNumberOfUnbilledLoans }
     * 
     */
    public WMCUWGetNumberOfUnbilledLoans createWMCUWGetNumberOfUnbilledLoans() {
        return new WMCUWGetNumberOfUnbilledLoans();
    }

    /**
     * Create an instance of {@link WMCUWGetNumberOfUnbilledLoansResponse }
     * 
     */
    public WMCUWGetNumberOfUnbilledLoansResponse createWMCUWGetNumberOfUnbilledLoansResponse() {
        return new WMCUWGetNumberOfUnbilledLoansResponse();
    }

    /**
     * Create an instance of {@link WMCUWListUnderwritersWithUnbilledLoans }
     * 
     */
    public WMCUWListUnderwritersWithUnbilledLoans createWMCUWListUnderwritersWithUnbilledLoans() {
        return new WMCUWListUnderwritersWithUnbilledLoans();
    }

    /**
     * Create an instance of {@link WMCUWListUnderwritersWithUnbilledLoansResponse }
     * 
     */
    public WMCUWListUnderwritersWithUnbilledLoansResponse createWMCUWListUnderwritersWithUnbilledLoansResponse() {
        return new WMCUWListUnderwritersWithUnbilledLoansResponse();
    }

    /**
     * Create an instance of {@link WMCUWListUnderwritersWithUnbilledLoansForDates }
     * 
     */
    public WMCUWListUnderwritersWithUnbilledLoansForDates createWMCUWListUnderwritersWithUnbilledLoansForDates() {
        return new WMCUWListUnderwritersWithUnbilledLoansForDates();
    }

    /**
     * Create an instance of {@link WMCUWListUnderwritersWithUnbilledLoansForDatesResponse }
     * 
     */
    public WMCUWListUnderwritersWithUnbilledLoansForDatesResponse createWMCUWListUnderwritersWithUnbilledLoansForDatesResponse() {
        return new WMCUWListUnderwritersWithUnbilledLoansForDatesResponse();
    }

    /**
     * Create an instance of {@link WMCUWUpdateLoanBillingStatus }
     * 
     */
    public WMCUWUpdateLoanBillingStatus createWMCUWUpdateLoanBillingStatus() {
        return new WMCUWUpdateLoanBillingStatus();
    }

    /**
     * Create an instance of {@link WMCUWUpdateLoanBillingStatusResponse }
     * 
     */
    public WMCUWUpdateLoanBillingStatusResponse createWMCUWUpdateLoanBillingStatusResponse() {
        return new WMCUWUpdateLoanBillingStatusResponse();
    }

}
