//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.06 at 10:46:28 PM EDT 
//


package com.radian.webserviceclient.cmd.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.radian.cuwb.ws.cmd.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.radian.cuwb.ws.cmd.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCustomer }
     * 
     */
    public GetCustomer createGetCustomer() {
        return new GetCustomer();
    }

    /**
     * Create an instance of {@link GetCustomerResponse }
     * 
     */
    public GetCustomerResponse createGetCustomerResponse() {
        return new GetCustomerResponse();
    }

    /**
     * Create an instance of {@link GetOnsitePricing }
     * 
     */
    public GetOnsitePricing createGetOnsitePricing() {
        return new GetOnsitePricing();
    }

    /**
     * Create an instance of {@link GetOnsitePricingResponse }
     * 
     */
    public GetOnsitePricingResponse createGetOnsitePricingResponse() {
        return new GetOnsitePricingResponse();
    }

    /**
     * Create an instance of {@link GetServiceCenterPricing }
     * 
     */
    public GetServiceCenterPricing createGetServiceCenterPricing() {
        return new GetServiceCenterPricing();
    }

    /**
     * Create an instance of {@link GetServiceCenterPricingResponse }
     * 
     */
    public GetServiceCenterPricingResponse createGetServiceCenterPricingResponse() {
        return new GetServiceCenterPricingResponse();
    }

    /**
     * Create an instance of {@link GetServiceTypes }
     * 
     */
    public GetServiceTypes createGetServiceTypes() {
        return new GetServiceTypes();
    }

    /**
     * Create an instance of {@link GetServiceTypesResponse }
     * 
     */
    public GetServiceTypesResponse createGetServiceTypesResponse() {
        return new GetServiceTypesResponse();
    }

    /**
     * Create an instance of {@link GetCustomerLocation }
     * 
     */
    public GetCustomerLocation createGetCustomerLocation() {
        return new GetCustomerLocation();
    }

    /**
     * Create an instance of {@link GetCustomerLocationResponse }
     * 
     */
    public GetCustomerLocationResponse createGetCustomerLocationResponse() {
        return new GetCustomerLocationResponse();
    }

    /**
     * Create an instance of {@link GetCostCenter }
     * 
     */
    public GetCostCenter createGetCostCenter() {
        return new GetCostCenter();
    }

    /**
     * Create an instance of {@link GetCostCenterResponse }
     * 
     */
    public GetCostCenterResponse createGetCostCenterResponse() {
        return new GetCostCenterResponse();
    }

    /**
     * Create an instance of {@link GetBillingProfile }
     * 
     */
    public GetBillingProfile createGetBillingProfile() {
        return new GetBillingProfile();
    }

    /**
     * Create an instance of {@link GetBillingProfileResponse }
     * 
     */
    public GetBillingProfileResponse createGetBillingProfileResponse() {
        return new GetBillingProfileResponse();
    }

    /**
     * Create an instance of {@link GetBillingProfiles }
     * 
     */
    public GetBillingProfiles createGetBillingProfiles() {
        return new GetBillingProfiles();
    }

    /**
     * Create an instance of {@link GetBillingProfilesResponse }
     * 
     */
    public GetBillingProfilesResponse createGetBillingProfilesResponse() {
        return new GetBillingProfilesResponse();
    }

    /**
     * Create an instance of {@link GetBillingProfileCoveredBranches }
     * 
     */
    public GetBillingProfileCoveredBranches createGetBillingProfileCoveredBranches() {
        return new GetBillingProfileCoveredBranches();
    }

    /**
     * Create an instance of {@link GetBillingProfileCoveredBranchesResponse }
     * 
     */
    public GetBillingProfileCoveredBranchesResponse createGetBillingProfileCoveredBranchesResponse() {
        return new GetBillingProfileCoveredBranchesResponse();
    }

    /**
     * Create an instance of {@link GetBillingProfileOnsites }
     * 
     */
    public GetBillingProfileOnsites createGetBillingProfileOnsites() {
        return new GetBillingProfileOnsites();
    }

    /**
     * Create an instance of {@link GetBillingProfileOnsitesResponse }
     * 
     */
    public GetBillingProfileOnsitesResponse createGetBillingProfileOnsitesResponse() {
        return new GetBillingProfileOnsitesResponse();
    }

    /**
     * Create an instance of {@link GetBillingProfileThirdParties }
     * 
     */
    public GetBillingProfileThirdParties createGetBillingProfileThirdParties() {
        return new GetBillingProfileThirdParties();
    }

    /**
     * Create an instance of {@link GetBillingProfileThirdPartiesResponse }
     * 
     */
    public GetBillingProfileThirdPartiesResponse createGetBillingProfileThirdPartiesResponse() {
        return new GetBillingProfileThirdPartiesResponse();
    }

    /**
     * Create an instance of {@link GetBillingProfilesLite }
     * 
     */
    public GetBillingProfilesLite createGetBillingProfilesLite() {
        return new GetBillingProfilesLite();
    }

    /**
     * Create an instance of {@link GetBillingProfilesLiteResponse }
     * 
     */
    public GetBillingProfilesLiteResponse createGetBillingProfilesLiteResponse() {
        return new GetBillingProfilesLiteResponse();
    }

    /**
     * Create an instance of {@link GetCodes }
     * 
     */
    public GetCodes createGetCodes() {
        return new GetCodes();
    }

    /**
     * Create an instance of {@link GetCodesResponse }
     * 
     */
    public GetCodesResponse createGetCodesResponse() {
        return new GetCodesResponse();
    }

    /**
     * Create an instance of {@link GetThirdPartySubmitterBilledInvestors }
     * 
     */
    public GetThirdPartySubmitterBilledInvestors createGetThirdPartySubmitterBilledInvestors() {
        return new GetThirdPartySubmitterBilledInvestors();
    }

    /**
     * Create an instance of {@link GetThirdPartySubmitterBilledInvestorsResponse }
     * 
     */
    public GetThirdPartySubmitterBilledInvestorsResponse createGetThirdPartySubmitterBilledInvestorsResponse() {
        return new GetThirdPartySubmitterBilledInvestorsResponse();
    }

}
