//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.19 at 05:04:49 PM GST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://radianmi.MionlineCUW/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.radian.webserviceclient.model;
